name: Release
on:
  release:
    types: [prereleased, released]

jobs:

  # Prepare and publish the plugin to JetBrains Marketplace repository
  release:
    name: Publish Bam
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Free GitHub Actions Environment Disk Space
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false

      # Check out the current repository
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Zip Folder
        run: |
          zip -r Bam_Catalcysm.zip . -x ".git/*" ".github/*"
      - name: Generate Release Notes
        id: notes
        uses: RedCrafter07/release-notes-action@v1.0.1
        with:
          tag-name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3.1.2
        with:
          file_path: "Bam_Catalcysm.zip"
          game_endpoint: "wow"
          project_id: "1158838"
          display_name: "Bam_Cataclysm_${{ github.event.release.tag_name }}"
          changelog: "${{ steps.notes.outputs.release-notes }}"
          release_type: release
          game_versions: "77522"
          token: ${{ secrets.CURSEFROG_API_TOKEN }}
